name: chat_gpt
description: "A new Flutter project. ChatGPT UI Clone for my portfolio."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.5.0-152

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  package_info_plus: ^8.0.0
  colornames:
  flutter_native_splash: ^2.4.1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  manager:
    path: ..//manager
  ollama_dart: ^0.2.2+1
  forui: ^0.8.0
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
